// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_device_name                      3
#define gattdb_board_serial                    16
#define gattdb_board_rev                       18
#define gattdb_firmware_rev                    20
#define gattdb_system_id                       22
#define gattdb_batt_measurement                25
#define gattdb_es_control_point                29
#define gattdb_power_source_type               33
#define gattdb_iaq_eco2                        36
#define gattdb_iaq_tvoc                        38
#define gattdb_iaq_control_point               40
#define gattdb_ui_buttons                      44
#define gattdb_ui_leds                         46
#define gattdb_ui_rgbleds                      49
#define gattdb_ui_control_point                52
#define gattdb_aio_digital_in                  56
#define gattdb_aio_digital_out                 61
#define gattdb_imu_acceleration                66
#define gattdb_imu_orientation                 69
#define gattdb_imu_control_point               72
#define gattdb_hall_state                      76
#define gattdb_hall_field_strength             79
#define gattdb_hall_control_point              82

#endif
