// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_device_name                      3
#define gattdb_board_serial                    16
#define gattdb_board_rev                       18
#define gattdb_firmware_rev                    20
#define gattdb_system_id                       22
#define gattdb_batt_measurement                25
#define gattdb_es_ambient_light                29
#define gattdb_es_sound_level                  31
#define gattdb_es_control_point                33
#define gattdb_power_source_type               37
#define gattdb_iaq_eco2                        40
#define gattdb_iaq_tvoc                        42
#define gattdb_iaq_control_point               44
#define gattdb_ui_buttons                      48
#define gattdb_ui_leds                         50
#define gattdb_ui_rgbleds                      53
#define gattdb_ui_control_point                56
#define gattdb_aio_digital_in                  60
#define gattdb_aio_digital_out                 65
#define gattdb_imu_acceleration                70
#define gattdb_imu_orientation                 73
#define gattdb_imu_control_point               76
#define gattdb_hall_state                      80
#define gattdb_hall_field_strength             83
#define gattdb_hall_control_point              86

#endif
